theme = "ayu_dark"

[editor]
bufferline = "multiple"
line-number = "relative"
mouse = false

[editor.smart-tab]
enable = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
