[[language]]
name = "nix"
auto-format = true
# formatter = { command = "nixfmt" }

[[language]]
name = "beancount"
auto-format = true
formatter = { command = "bean-format" }

[[language]]
name = "lua"
auto-format = true
formatter = { command = "lua-format" }

[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = ["--quiet", "-"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md", "--config", "~/.config/dprint/config.json"]}

[[language]]
name = "rust"
auto-format = true
formatter = { command = "cargo +nightly fmt" }

[[language]]
name = "go"
auto-format = true
formatter = { command = "gofmt" }
language-servers = ["gopls", "golangci-lint2-langserver"]

[language-server.golangci-lint2-langserver]
command = "golangci-lint-langserver"

[language-server.golangci-lint2-langserver.config]
command = [
  "golangci-lint",
  "run",
  "--output.json.path",
  "stdout",
  "--show-stats=false",
  "--issues-exit-code=1",
]
